# Generated by Django 4.2.7 on 2026-02-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_permission_role_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=0, max_length=11, unique=True, verbose_name='手机号'),
            preserve_default=False,
        ),
    ]
