# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('source_type', models.CharField(max_length=50, verbose_name='数据源类型')),
                ('config', models.JSONField(default=dict, verbose_name='配置信息')),
                ('status', models.CharField(choices=[('待开发', '待开发'), ('开发中', '开发中'), ('已完成', '已完成'), ('已暂停', '已暂停')], default='待开发', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'data_sources',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='任务名称')),
                ('schedule', models.CharField(help_text='Cron表达式', max_length=100, verbose_name='调度规则')),
                ('status', models.CharField(choices=[('待开发', '待开发'), ('开发中', '开发中'), ('已完成', '已完成'), ('已暂停', '已暂停')], default='待开发', max_length=20, verbose_name='状态')),
                ('last_run_time', models.DateTimeField(blank=True, null=True, verbose_name='最后运行时间')),
                ('next_run_time', models.DateTimeField(blank=True, null=True, verbose_name='下次运行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_tasks', to=settings.AUTH_USER_MODEL)),
                ('data_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='data_management.datasource')),
            ],
            options={
                'verbose_name': '数据采集任务',
                'verbose_name_plural': '数据采集任务',
                'db_table': 'data_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(verbose_name='数据内容')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='data_management.datatask')),
            ],
            options={
                'verbose_name': '数据记录',
                'verbose_name_plural': '数据记录',
                'db_table': 'data_records',
                'ordering': ['-collected_at'],
            },
        ),
    ]
