# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=200, verbose_name='关键词')),
                ('filters', models.JSONField(default=dict, verbose_name='筛选条件')),
                ('result_count', models.IntegerField(default=0, verbose_name='结果数量')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='查询时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_queries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '岗位查询记录',
                'verbose_name_plural': '岗位查询记录',
                'db_table': 'position_queries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='岗位名称')),
                ('company', models.CharField(max_length=200, verbose_name='公司名称')),
                ('location', models.CharField(max_length=100, verbose_name='工作地点')),
                ('salary_range', models.CharField(max_length=100, verbose_name='薪资范围')),
                ('position_type', models.CharField(choices=[('全职', '全职'), ('兼职', '兼职'), ('实习', '实习'), ('合同', '合同')], max_length=20, verbose_name='岗位类型')),
                ('requirements', models.TextField(verbose_name='岗位要求')),
                ('description', models.TextField(verbose_name='岗位描述')),
                ('benefits', models.TextField(blank=True, verbose_name='福利待遇')),
                ('education', models.CharField(max_length=50, verbose_name='学历要求')),
                ('experience', models.CharField(max_length=50, verbose_name='经验要求')),
                ('industry', models.CharField(max_length=100, verbose_name='所属行业')),
                ('source_url', models.URLField(blank=True, verbose_name='来源链接')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '岗位信息',
                'verbose_name_plural': '岗位信息',
                'db_table': 'positions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company'], name='positions_company_3b6f6c_idx'), models.Index(fields=['industry'], name='positions_industr_6918a0_idx'), models.Index(fields=['location'], name='positions_locatio_21e68f_idx')],
            },
        ),
        migrations.CreateModel(
            name='FavoritePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='收藏时间')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='position_data.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '收藏岗位',
                'verbose_name_plural': '收藏岗位',
                'db_table': 'favorite_positions',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'position')},
            },
        ),
    ]
