# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='算法名称')),
                ('algorithm_type', models.CharField(choices=[('recommendation', '推荐算法'), ('prediction', '预测分析'), ('classification', '分类分析'), ('clustering', '聚类分析'), ('sentiment', '情感分析'), ('nlp', '自然语言处理')], max_length=50, verbose_name='算法类型')),
                ('description', models.TextField(verbose_name='算法描述')),
                ('parameters', models.JSONField(default=dict, verbose_name='算法参数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'AI算法',
                'verbose_name_plural': 'AI算法',
                'db_table': 'ai_algorithms',
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('input_data', models.JSONField(verbose_name='输入数据')),
                ('algorithm_type', models.CharField(blank=True, max_length=50, verbose_name='算法类型')),
                ('parameters', models.JSONField(default=dict, verbose_name='任务参数')),
                ('status', models.CharField(choices=[('待开发', '待开发'), ('处理中', '处理中'), ('已完成', '已完成'), ('失败', '失败')], default='待开发', max_length=20, verbose_name='状态')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='分析结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('algorithm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ai_analysis.aialgorithm')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI分析任务',
                'verbose_name_plural': 'AI分析任务',
                'db_table': 'ai_analysis_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_type', models.CharField(max_length=100, verbose_name='结果类型')),
                ('data', models.JSONField(verbose_name='结果数据')),
                ('metrics', models.JSONField(blank=True, default=dict, verbose_name='评估指标')),
                ('visualization_data', models.JSONField(blank=True, default=dict, verbose_name='可视化数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_details', to='ai_analysis.aianalysistask')),
            ],
            options={
                'verbose_name': 'AI分析结果',
                'verbose_name_plural': 'AI分析结果',
                'db_table': 'ai_analysis_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
