# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry', models.CharField(max_length=100, unique=True, verbose_name='行业名称')),
                ('total_positions', models.IntegerField(default=0, verbose_name='岗位总数')),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='平均薪资')),
                ('top_companies', models.JSONField(default=list, verbose_name='热门公司')),
                ('hot_skills', models.JSONField(default=list, verbose_name='热门技能')),
                ('growth_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='增长率')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '行业统计',
                'verbose_name_plural': '行业统计',
                'db_table': 'industry_statistics',
            },
        ),
        migrations.CreateModel(
            name='StatisticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='报告标题')),
                ('report_type', models.CharField(choices=[('行业分析', '行业分析'), ('薪资分析', '薪资分析'), ('地域分析', '地域分析'), ('趋势分析', '趋势分析'), ('综合分析', '综合分析')], max_length=50, verbose_name='报告类型')),
                ('parameters', models.JSONField(default=dict, verbose_name='分析参数')),
                ('result_data', models.JSONField(default=dict, verbose_name='结果数据')),
                ('charts', models.JSONField(default=list, verbose_name='图表数据')),
                ('summary', models.TextField(blank=True, verbose_name='摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '统计报告',
                'verbose_name_plural': '统计报告',
                'db_table': 'statistics_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200, verbose_name='岗位名称')),
                ('location', models.CharField(max_length=100, verbose_name='地点')),
                ('min_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最低薪资')),
                ('max_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='最高薪资')),
                ('avg_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='平均薪资')),
                ('median_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='中位数薪资')),
                ('sample_size', models.IntegerField(default=0, verbose_name='样本数量')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '薪资统计',
                'verbose_name_plural': '薪资统计',
                'db_table': 'salary_statistics',
                'unique_together': {('position_title', 'location')},
            },
        ),
    ]
