# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', '调试'), ('INFO', '信息'), ('WARNING', '警告'), ('ERROR', '错误'), ('CRITICAL', '严重')], max_length=20, verbose_name='日志级别')),
                ('message', models.TextField(verbose_name='日志消息')),
                ('module', models.CharField(blank=True, max_length=100, null=True, verbose_name='模块')),
                ('error_trace', models.TextField(blank=True, null=True, verbose_name='错误堆栈')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'db_table': 'system_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level'], name='system_logs_level_245244_idx'), models.Index(fields=['module'], name='system_logs_module_ac9b9d_idx'), models.Index(fields=['created_at'], name='system_logs_created_2e006d_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('查询', '查询'), ('新增', '新增'), ('修改', '修改'), ('删除', '删除'), ('导出', '导出'), ('登录', '登录'), ('登出', '登出'), ('导入', '导入'), ('授权', '授权'), ('取消授权', '取消授权')], max_length=20, verbose_name='操作类型')),
                ('module', models.CharField(max_length=50, verbose_name='模块')),
                ('description', models.TextField(verbose_name='操作描述')),
                ('status', models.CharField(choices=[('成功', '成功'), ('失败', '失败'), ('警告', '警告')], default='成功', max_length=20, verbose_name='操作状态')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='IP地址')),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True, verbose_name='用户代理')),
                ('request_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='请求路径')),
                ('request_method', models.CharField(blank=True, max_length=20, null=True, verbose_name='请求方法')),
                ('response_code', models.IntegerField(blank=True, null=True, verbose_name='响应代码')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='执行时间(ms)')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='额外数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'operation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'action_type'], name='operation_l_user_id_207273_idx'), models.Index(fields=['module', 'status'], name='operation_l_module_db453e_idx'), models.Index(fields=['created_at'], name='operation_l_created_3fec78_idx')],
            },
        ),
    ]
