# Generated by Django 4.2.7 on 2026-02-09 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='仪表盘名称')),
                ('description', models.TextField(blank=True, verbose_name='仪表盘描述')),
                ('layout', models.JSONField(default=list, verbose_name='布局配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '仪表盘',
                'verbose_name_plural': '仪表盘',
                'db_table': 'dashboards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChartComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='图表名称')),
                ('chart_type', models.CharField(choices=[('line', '折线图'), ('bar', '柱状图'), ('pie', '饼图'), ('scatter', '散点图'), ('radar', '雷达图'), ('area', '面积图'), ('gauge', '仪表盘'), ('heatmap', '热力图'), ('treemap', '树图')], max_length=20, verbose_name='图表类型')),
                ('data_source_type', models.CharField(choices=[('api', 'API接口'), ('model', '数据库模型'), ('static', '静态数据')], default='api', max_length=20, verbose_name='数据源类型')),
                ('data_source', models.JSONField(verbose_name='数据源配置')),
                ('options', models.JSONField(default=dict, verbose_name='图表选项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chart_components', to=settings.AUTH_USER_MODEL)),
                ('dashboard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charts', to='visualization.dashboard')),
            ],
            options={
                'verbose_name': '图表组件',
                'verbose_name_plural': '图表组件',
                'db_table': 'chart_components',
                'ordering': ['-created_at'],
            },
        ),
    ]
